### ISSUE TITLE
How to use as module in Ti?

### ISSUE THREAD

**Issue by focussing** [hansemannn/titanium-exif#1]
Good morning @hansemannn!

Could you give some explanation about how to use this in an app?
It has not the same format as other modules, or should I put it in the lib folder?

Best regards!

**Comment by hansemannn** [comment]
It is iOS only. You can find the latest release [here](https://github.com/hansemannn/titanium-exif/releases), but I haven't worked on it for quite a while.

**Comment by focussing** [comment]
Thanks, I tested it; but it returns only empty info.
Note: images on iOS are in PNG format; would that be of influence?
